# -*- coding: utf-8 -*-
"""ProjetoBleuDetetive.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TdrGc9uywkrODs0tiEe-ZQFZKX-4Mj7w
"""

resposta1 = str(input('Você telefonou para a vítima? [sim/não] ')).strip().upper()
print()
while resposta1 != 'SIM' and resposta1 !='NÃO':
    print('Responda apenas "sim" ou "não"')
    print()
    if resposta1 != 'SIM' and resposta1 !='NÃO':
        resposta1 =str(input('Você telefonou para a vítima? [sim/não] ')).strip().upper()
        print()
else: resposta2 = str(input('Você esteve no local do crime? [sim/não] ')).strip().upper()
print()
while resposta2 != 'SIM' and resposta2 !='NÃO':
    print('Responda apenas "sim" ou "não"')
    print()
    if resposta2 != 'SIM' and resposta2 !='NÃO':
        resposta2 =str(input('Você esteve no local do crime? [sim/não] ')).strip().upper()
        print()
else: resposta3 = str(input('Você mora perto da vítima? [sim/não] ')).strip().upper()
print()
while resposta3 != 'SIM' and resposta3 !='NÃO':
    print('Responda apenas "sim" ou "não"')
    print()
    if resposta3 != 'SIM' and resposta3 !='NÃO':
        resposta3 =str(input('Você mora perto da vítima? [sim/não] ')).strip().upper()
        print()
else: resposta4 = str(input('Você devia para a vítima? [sim/não] ')).strip().upper()
print()
while resposta4 != 'SIM' and resposta4 != 'NÃO':
    print('Responda apenas "sim" ou "não"')
    print()
    if resposta4 != 'SIM' and resposta4 !='NÃO':
        resposta4 =str(input('Você devia para a vítima? [sim/não] ')).strip().upper()
        print()
else: resposta5 = str(input('Você já trabalhou com a vítima? [sim/não] ')).strip().upper()
print()
while resposta5 != 'SIM' and resposta5 !='NÃO':
    print('Responda apenas "sim" ou "não"')
    print()
    if resposta5 != 'SIM' and resposta5 !='NÃO':
        resposta4 =str(input('Você já trabalhou com a vítima? [sim/não] ')).strip().upper()
        print()
        break
print('Fim do interrogatorio')
print()
print('O interrogado é considerado:')            

a = 'SIM'
b = 'NÂO'


if resposta1 == a:
    if resposta2 == a:
        if resposta3 == a:
            if resposta4 == a:
                if resposta5 == a:            
                    print('Culpado')
                else:
                    print('Cúmplice')
            else:
                if resposta5 == a:
                    print('Cúmplice')
                else:
                    print('Cúmplice')   
        else:
            if resposta4 == a:
                if resposta5 == a:
                    print('Cúmplice')
                else:
                    print('Cúmplice')          
            else:
                if resposta5 == a:
                    print('Cúmplice')    
                else:
                    print('Suspeita')
    else:
        if resposta3 == a:               
            if resposta4 == a:
                if resposta5 == a:            
                    print('Cúmplice')
                else:
                    print('Cúmplice')    
            else:
                if resposta5 == a:
                    print('Cúmplice')
                else:
                    print('Suspeita')        
        else:            
            if resposta4 == a:
                if resposta5 == a:
                    print('Cúmplice')
                else:
                    print('Suspeita')
            else:
                if resposta5 == a:
                    print('Suspeita') 
                else:
                    print('Inocente')
else:
    if resposta2 == a:
        if resposta3 == a:
            if resposta4 == a:
                if resposta5 == a:            
                    print('Cúmplice')
                else:
                    print('Cúmplice')    
            else:
                if resposta5 == a:            
                    print('Cúmplice')
                else:
                    print('Suspeita')                
        else:
            if resposta4 == a:
                if resposta5 == a:
                    print('Cúmplice') 
                else:
                    print('Suspeita')  
            else:
                if resposta5 == a:
                    print('Suspeita')
                else:
                    print('Inocente')                  
    else:
        if resposta3 == a:
            if resposta4 == a:
                if resposta5 == a:            
                    print('Cúmplice')
                else:
                    print('Suspeita') 
            else:
                if resposta5 == a:
                    print('Suspeita')
                else:
                    print('Inocente')             
        else:
            if resposta4 == a:
                if resposta5 == a:            
                    print('Suspeita')
                else:
                    print('Inocente')    
            else:
                if resposta5 == a:            
                    print('Inocente')
                else:
                    print('Inocente')

print()   
print('Fim do programa')
print()